### ISSUE TITLE
Branch ("develop") definition does not exist in the config.

### ISSUE THREAD

**Issue by JamieMason** [gajus/gitdown#27]
Hi @gajus, thanks for creating this.

I'm trying this for the first time and having some problems I could use some help with please.

I created the following in a `Gruntfile.js`.

``` javascript
grunt.registerTask('gitdown', 'Generate README using gitdown.', function() {

  var Gitdown = require('gitdown');
  var gitdown = Gitdown.read('.gitdown/README.md');

  gitdown.write('README.md');

});
```

Which can be run with `grunt gitdown`.

I'm on the `develop` branch of a local clone of https://github.com/JamieMason/Jasmine-Matchers/tree/develop and the contents of my `.gitdown/README.md` don't seem to matter, I receive the following error.

```
Running "gitdown" task

Possibly unhandled Error: Branch ("develop") definition does not exist in the config.
    at Gitinfo.gitinfo.remoteURL (/Users/jamie/Sites/Jasmine-Matchers/node_modules/gitdown/node_modules/gitinfo/src/gitinfo.js:65:19)
    at Gitinfo.gitinfo.username (/Users/jamie/Sites/Jasmine-Matchers/node_modules/gitdown/node_modules/gitinfo/src/gitinfo.js:92:54)
    at Gitinfo.gitinfo.url (/Users/jamie/Sites/Jasmine-Matchers/node_modules/gitdown/node_modules/gitinfo/src/gitinfo.js:21:48)
    at Object.helper.compile (/Users/jamie/Sites/Jasmine-Matchers/node_modules/gitdown/src/helpers/gitinfo.js:23:32)
    at Gitdown.gitdown._resolveURLs (/Users/jamie/Sites/Jasmine-Matchers/node_modules/gitdown/src/gitdown.js:99:33)
    at /Users/jamie/Sites/Jasmine-Matchers/node_modules/gitdown/src/gitdown.js:35:32
    at tryCatcher (/Users/jamie/Sites/Jasmine-Matchers/node_modules/gitdown/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/jamie/Sites/Jasmine-Matchers/node_modules/gitdown/node_modules/bluebird/js/main/promise.js:475:31)
    at Promise._settlePromiseAt (/Users/jamie/Sites/Jasmine-Matchers/node_modules/gitdown/node_modules/bluebird/js/main/promise.js:554:18)
    at Async._drainQueue (/Users/jamie/Sites/Jasmine-Matchers/node_modules/gitdown/node_modules/bluebird/js/main/async.js:84:12)
    at Async._drainQueues (/Users/jamie/Sites/Jasmine-Matchers/node_modules/gitdown/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/Users/jamie/Sites/Jasmine-Matchers/node_modules/gitdown/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3

Done, without errors.
```

The value of `gitdown.config` is.

``` javascript
{
  headingNesting: {
    enabled: true
  },
  variable: {
    scope: {}
  },
  deadlink: {
    findDeadURLs: false,
    findDeadFragmentIdentifiers: false
  },
  gitinfo: {
    gitPath: '/Users/jamie/Sites/Jasmine-Matchers'
  }
}
```

**Comment by gajus** [comment]
This error is referring to `.git/config` file, not your `gitdown.config`. It says that although you are on a branch called "develop", there is no information about such branch in git configuration.

Do you mind sharing the config file?

**Comment by JamieMason** [comment]
Sure, it's as follows.

```
[core]
  repositoryformatversion = 0
  filemode = true
  bare = false
  logallrefupdates = true
  ignorecase = true
[remote "origin"]
  fetch = +refs/heads/*:refs/remotes/origin/*
  url = git@github.com:JamieMason/Jasmine-Matchers.git
  gtPushAllTags = true
  gtPruneOnFetch = true
  gtAlwaysFetchAllTags = true
[mergetool "tower"]
  cmd = \"/Applications/Tower.app/Contents/Resources/diffmerge.sh\" \"$LOCAL\" \"$REMOTE\" \"$BASE\" \"$MERGED\"
  trustExitCode = true
[difftool "tower"]
  cmd = \"/Applications/Tower.app/Contents/Resources/CompareScripts/filemerge.sh\" \"$LOCAL\" \"$REMOTE\"
[branch "master"]
  remote = origin
  merge = refs/heads/master
```

I've not really delved into this before, is there anything not here I should really be using?

Thanks a lot @gajus.

**Comment by gajus** [comment]
I am guessing that you have not setup remote URL for the develop branch? Gitdown is expecting this in order to be able to construct URLs for that branch.

**Comment by gajus** [comment]
@JamieMason Do you still need help with this?

**Comment by JamieMason** [comment]
Thanks @gajus I will close this.

**Comment by djabor** [comment]
this is still an issue.

i have cases where we build hotfix branches or others that have no remotely tracked counterpart.
added to that, we are using this project specifically to insert data from package.json rather than git info.

it seems redundant to check for remot tracking config when this feature is not used.
