### ISSUE TITLE
breaking changes: 1.3.1/1.3.2

### ISSUE THREAD

**Issue by mdreizin** [gajus/gitdown#30]
I have just upgraded to `1.3.2` and it doesn't work. It looks like you have made breaking changes on `1.3.1`.

I have got the following error:

```
TypeError: undefined is not a function
    at Function.MarkdownContents.tree (~/webpack-config/node_modules/gitdown/node_modules/markdown-contents/src/markdown-contents.js:98:21)
    at Function.Gitdown._nestHeadingIds (~/webpack-config/node_modules/gitdown/src/gitdown.js:268:47)
    at ~/webpack-config/node_modules/gitdown/src/gitdown.js:36:40
    at tryCatcher (~/webpack-config/node_modules/gitdown/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (~/webpack-config/node_modules/gitdown/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (~/webpack-config/node_modules/gitdown/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (~/webpack-config/node_modules/gitdown/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (~/webpack-config/node_modules/gitdown/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (~/webpack-config/node_modules/gitdown/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by gajus** [comment]
```
at Function.MarkdownContents.tree (~/webpack-config/node_modules/gitdown/node_modules/markdown-contents/src/markdown-contents.js:98:21)
```

The issue appears to be coming from the https://github.com/gajus/markdown-contents.

There is not enough context though. @mdreizin, please produce a repository that I could pull to reproduce the issue.

**Comment by mdreizin** [comment]
@gajus It works fine on `1.3`.

You can just check out this repo https://github.com/mdreizin/webpack-config and just change `"gitdown": "^1.3.0"` to `"gitdown": "^1.3.2"`.

**Comment by gajus** [comment]
https://github.com/gajus/contents package built was malformed. 1.3.3 fixes the issue.

**Comment by mdreizin** [comment]
@gajus Thank you very much for a quick fix, but I have got the following issue:

```
[16:48:26] ~/webpack-config/node_modules/gitdown/node_modules/deadlink/node_modules/jsdom/lib/jsdom.js:3
`jsdom 4.x onward only works on io.js, not Node.js™: https://github.com/tmpvar
^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (~/webpack-config/node_modules/gitdown/node_modules/deadlink/src/deadlink.js:10:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at gitdown._resolveURLs (~/webpack-config/node_modules/gitdown/src/gitdown.js:96:24)
    at ~/webpack-config/node_modules/gitdown/src/gitdown.js:40:22
```

```
node -v
v0.12.7
```

**Comment by gajus** [comment]
Time to upgrade to V4, https://medium.com/node-js-javascript/4-0-is-the-new-1-0-386597a3436d.

Or simply force an older version of Gitdown.

**Comment by mdreizin** [comment]
@gajus for my point of view `gitdown` should use `SemVer` to prevent any issues like this.

**Comment by gajus** [comment]
I agree. That said, the breaking change comes from a dependency. It is close to impossible to catch these things.
