### ISSUE TITLE
"Cannot get the current branch name." on travis-ci

### ISSUE THREAD

**Issue by mdreizin** [gajus/gitdown#36]
Could you please tell me how to find workaround for that?

`travis-ci` uses:

```
git clone --depth=50 --branch=master https://github.com/mdreizin/webpack-config.git mdreizin/webpack-config
cd mdreizin/webpack-config
git checkout -qf 9ccb6cdb8cba6519d38df68d2b785ee7cf0aeab2
npm run doc
```

```
Error: Cannot get the current branch name.
    at Object.gitinfo.branch (/home/travis/build/mdreizin/webpack-config/node_modules/gitdown/node_modules/gitinfo/src/gitinfo.js:51:19)
    at Object.gitinfo.remoteURL (/home/travis/build/mdreizin/webpack-config/node_modules/gitdown/node_modules/gitinfo/src/gitinfo.js:63:34)
    at Object.gitinfo.username (/home/travis/build/mdreizin/webpack-config/node_modules/gitdown/node_modules/gitinfo/src/gitinfo.js:98:51)
    at Object.helper.compile (/home/travis/build/mdreizin/webpack-config/node_modules/gitdown/src/helpers/gitinfo.js:25:32)
    at Object.services.travis (/home/travis/build/mdreizin/webpack-config/node_modules/gitdown/src/helpers/badge.js:98:34)
    at Object.helper.compile (/home/travis/build/mdreizin/webpack-config/node_modules/gitdown/src/helpers/badge.js:150:33)
    at /home/travis/build/mdreizin/webpack-config/node_modules/gitdown/src/parser.js:184:54
    at Array.forEach (native)
    at Parser.parser.execute (/home/travis/build/mdreizin/webpack-config/node_modules/gitdown/src/parser.js:173:30)
    at Parser.parser.play (/home/travis/build/mdreizin/webpack-config/node_modules/gitdown/src/parser.js:49:22)
    at Gitdown.gitdown.get (/home/travis/build/mdreizin/webpack-config/node_modules/gitdown/src/gitdown.js:31:14)
    at Gitdown.gitdown.write (/home/travis/build/mdreizin/webpack-config/node_modules/gitdown/src/gitdown.js:55:14)
    at Gulp.<anonymous> (/home/travis/build/mdreizin/webpack-config/gulpfile.js:20:47)
    at module.exports (/home/travis/build/mdreizin/webpack-config/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/travis/build/mdreizin/webpack-config/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/travis/build/mdreizin/webpack-config/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
```

**Comment by breerly** [comment]
You might try this workaround - http://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/
