### ISSUE TITLE
Error: Input file does not exist.

### ISSUE THREAD

**Issue by mdreizin** [gajus/gitdown#37]
@gajus

I got error:

```
Error: Input file does not exist.
    at Object.helper.compile (/Users/mdreizin/Developer/src/github.com/webpack-config/node_modules/gitdown/src/helpers/include.js:30:15)
    at /Users/mdreizin/Developer/src/github.com/webpack-config/node_modules/gitdown/src/parser.js:184:54
    at Array.forEach (native)
    at parser.execute (/Users/mdreizin/Developer/src/github.com/webpack-config/node_modules/gitdown/src/parser.js:173:30)
    at parser.play (/Users/mdreizin/Developer/src/github.com/webpack-config/node_modules/gitdown/src/parser.js:49:22)
    at /Users/mdreizin/Developer/src/github.com/webpack-config/node_modules/gitdown/src/parser.js:60:31
    at tryCatcher (/Users/mdreizin/Developer/src/github.com/webpack-config/node_modules/gitdown/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/mdreizin/Developer/src/github.com/webpack-config/node_modules/gitdown/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/mdreizin/Developer/src/github.com/webpack-config/node_modules/gitdown/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/mdreizin/Developer/src/github.com/webpack-config/node_modules/gitdown/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/mdreizin/Developer/src/github.com/webpack-config/node_modules/gitdown/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/mdreizin/Developer/src/github.com/webpack-config/node_modules/gitdown/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/mdreizin/Developer/src/github.com/webpack-config/node_modules/gitdown/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

using the following snippet:

```js
gulp.task('docs-readme', function() {
    return Gitdown.readFile(path.resolve('./.gitdown/README.md')).writeFile(path.resolve('./README.md'));
});
```

```
node v5.6.0
npm v3.6.0
```

```
"gitdown": "^2.4.0",
```

**Comment by mdreizin** [comment]
@gajus It looks like most stable version is `1.3.0`.
